package

public inline fun myCatchIOException(/*0*/ block: () -> kotlin.Unit): kotlin.Unit
    CallsInPlace(block, EXACTLY_ONCE)
    blockkotlin.Unit consumes Consumer of IOExceptionkotlin.Unit

public inline fun myCatchRuntimeException(/*0*/ block: () -> kotlin.Unit): kotlin.Unit
    CallsInPlace(block, EXACTLY_ONCE)
    blockkotlin.Unit consumes Consumer of RuntimeExceptionkotlin.Unit

public fun test_3(): kotlin.Unit
public fun throwsFileNotFoundException(): kotlin.Unit
    Supplier of FileNotFoundException

public fun throwsIOException(): kotlin.Unit
    Supplier of IOException

public fun throwsNullPointerException(): kotlin.Unit
    Supplier of NullPointerException

